CREATE TABLE IF NOT EXISTS article(
    id INT AUTO_INCREMENT,
    author VARCHAR(25) NOT NULL,
    title VARCHAR(50) NOT NULL,
    content VARCHAR(500) NOT NULL,
    createdAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);